feature: Add support for including specific columns in audit report
jeemok/better-npm-audit pull request #100
Opened 2024-08-31 09:52 UTC by GauravChinavle

- Changed column name from "Sev." to "Severity"
- Implemented the `-i` flag to specify columns to include in the audit report
- Now, users can choose to include selected columns like Module, Title, and Severity by using the `-i` option
- Example usage: `better-npm-audit audit -i Module,Title,Severity`

2024-09-01 14:16 UTC, jeemok commented
Thank you for your contribution, @GauravChinavle ! :) 

PR looks good to me, but there's a new vulnerability just reported and we have audit check running in our pipeline:
- micromatch <4.0.8
- Severity: moderate
- Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
- fix available via npm audit fix
- node_modules/micromatch
- 1 moderate severity vulnerability

Can you run `npm audit fix` and commit the fix please?

and can you also include the new flag `-i` into `README.md` please?

2024-09-01 14:17 UTC, jeemok requested changes

2024-09-03 05:53 UTC, GauravChinavle commented on package.json
> -    "prebuild": "npm run qc && npm run clean",
apologies. had removed it for qucik testing. 
this is retained now.

2024-09-03 07:33 UTC, jeemok approved these changes

2024-09-03 07:33 UTC, jeemok commented
thank you @GauravChinavle !

2024-09-03 07:33 UTC, merged